CREATE TABLE IF NOT EXISTS public.book_author
(
    authorid integer NOT NULL,
    bookid integer NOT NULL,
    CONSTRAINT book_author_pkey PRIMARY KEY (authorid, bookid),
    FOREIGN KEY (authorid) REFERENCES public.author(authorid),
    FOREIGN KEY (bookid) REFERENCES public.book(bookid)
);

DROP TABLE public.book_author;

CREATE TABLE IF NOT EXISTS public.book
(
    bookid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bookname varchar(100),
    genre varchar(100)
);

CREATE TABLE IF NOT EXISTS public.author
(
    authorid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    authorfullname varchar(100)
);